name: "Deployment"

on:
  workflow_dispatch:

concurrency:
  # Ensure only one deployment is running at a time
  group: ${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: read
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.ref_name }}
      - name: Setup
        uses: actions/setup-node@v6
        with:
          cache: "npm"
          cache-dependency-path: package-lock.json
      - name: Install deps
        run: npm install
      - name: Build
        run: npm run build
      - name: Deploy to Siteground via FTP
        uses: SamKirkland/FTP-Deploy-Action@a51268f67f6605236975928ae28b0f7e9971d50a #v4.3.6
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          local-dir: dist/
